help_url: "http://www.railstutorial.org/help"
home_url: "http://www.railstutorial.org/"
VALID_EMAIL_REGEX: '\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z'
name_max_length: 50
email_max_length: 255
min_password_length: 6
image_url: "http://gravatar.com/emails"
gravatar:
  size_30: 30
  size: 80
  list_size: 50
mailer_from: "noreply@example.com"
password_reset_expired: 2
digit_140: 140
digit_50: 50
page_10: 10
img_size: 5
img_display_size: [500, 500]
